# Names of all participants
participants:
  - Christian
  - Claude
  - Hugo
  - Isabelle
  - Jean
  - Julien
  - Lucie
  - Marie
  - Nicolas

# The persons in the same group cannot exchange gifts between them
forbidden_groups:
  -
    - Isabelle
    - Hugo
    - Nicolas
    - Lucie
  -
    - Christian
    - Marie
  -
    - Jean
    - Claude

# Forbidden transaction, meaning a particular person cannot give to another particular person,
# described as a list of couples (giver, receiver)
forbidden_transactions:
  # Forbid the same attributions as Christmas 2021
  -
    giver: Julien
    receiver: Marie
  -
    giver: Lucie
    receiver: Christian
  -
    giver: Christian
    receiver: Nicolas
  -
    giver: Nicolas
    receiver: Jean
  -
    giver: Isabelle
    receiver: Julien
  -
    giver: Jean
    receiver: Hugo
  -
    giver: Marie
    receiver: Lucie
  -
    giver: Hugo
    receiver: Claude
  -
    giver: Claude
    receiver: Isabelle
